### ISSUE TITLE
no image in FAHViewer

### ISSUE THREAD

**Issue by jimerickson** [ChristianVirtual/FAH_WrapperGPUTrajectory#1]
i am using fedora 22 i followed the directions and the console shows a pyon heartbeat when the viewer is running but no image appears. i realize this is in developement but i have wanted this for a long time and would really like to get it working. thanks for all you do!

**Comment by jimerickson** [comment]
ok ChristianVirtual now i am getting an image i had it in the wrong mode for rendering. works fine if in "3", "stick" mode. thanks again!!

**Comment by ChristianVirtual** [comment]
Make sure you don't see the demo protein ? Can you share a screenshot ?

**Comment by jimerickson** [comment]
sure
![screenshot from 2015-12-23 15-43-31](https://cloud.githubusercontent.com/assets/527719/11985595/fd7ee220-a98b-11e5-94cf-9fcba3856c0d.png)

**Comment by ChristianVirtual** [comment]
Thanks, looks right.
